#-*- coding: utf-8 -*-
'''
Allgemeine Indexierung der Spatial Indexe

@author: Daniel Zinniker

@note: 



'''



# Variabeln

def_array=[]



def_array.append(['/ELE/ELET_ENDVBR_KLEMME' , 'Polyline' , [1000], 0])
def_array.append(['/ELE/ELET_KABEL_TRASSE' , 'Polyline' , [250], 0])
def_array.append(['/ELE/ELET_NAME_STATION' , 'Polyline' , [1000], 0])
def_array.append(['/ELE/ELET_NR_BAUOBJEKT' , 'Polyline' , [1000], 0])
def_array.append(['/ELE/ELET_NR_FREILTGABLEITER' , 'Polyline' , [1000], 0])
def_array.append(['/ELE/ELET_NR_HAUSANSCHLUSS' , 'Polyline' , [1000], 0])
def_array.append(['/ELE/ELET_NR_KLEINANSCHLUSS' , 'Polyline' , [1000], 0])
def_array.append(['/ELE/ELET_NR_KLEMME' , 'Polyline' , [1000], 0])
def_array.append(['/ELE/ELET_NR_LEUCHTE' , 'Polyline' , [500], 0])
def_array.append(['/ELE/ELET_NR_SCHACHT' , 'Polyline' , [1000], 0])
def_array.append(['/ELE/ELET_NR_STATION' , 'Polyline' , [1000], 0])
def_array.append(['/ELE/ELET_NR_TRAGWERK' , 'Polyline' , [1000], 0])
def_array.append(['/ELE/ELET_NR_TRENNPUNKT' , 'Polyline' , [1000], 0])
def_array.append(['/ELE/ELET_QS_KABEL' , 'Polyline' , [500], 140140])
def_array.append(['/ELE/ELET_QS_KABELSCHUTZPOS' , 'Polyline' , [500], 0])
def_array.append(['/ELE/ELET_QS_ROHR' , 'Polyline' , [500], 0])
def_array.append(['/ELE/ELET_QS_ROHR_ROHR' , 'Polyline' , [1000], 0])
def_array.append(['/ELE/ELET_TEXT' , 'Polyline' , [1000], 0])
def_array.append(['/ELE/ELET_TXT_DSTRENNPUNKT' , 'Polyline' , [500], 0])
def_array.append(['/ELE/ELET_TXT_ERDUNG' , 'Polyline' , [1000], 0])
def_array.append(['/ELE/ELET_TXT_KABEL' , 'Polyline' , [500], 0])
def_array.append(['/ELE/ELET_TXT_MUFFE' , 'Polyline' , [1000], 0])
def_array.append(['/ELE/ELET_TXT_QUELLE' , 'Polyline' , [1000], 0])
def_array.append(['/ELE/ELET_TXT_ROHR' , 'Polyline' , [1000], 290])
def_array.append(['/ELE/ELET_TXT_TRANSFORMER' , 'Polyline' , [1000], 0])
def_array.append(['/ELE/ELET_TXT_TRASSE' , 'Polyline' , [1000], 0])
def_array.append(['/ELE/ELET_TXT_UEBERGANG' , 'Polyline' , [1000], 0])
def_array.append(['/ELE/ELET_TYP_KLEINANSCHLUSS' , 'Polyline' , [1000], 0])
def_array.append(['/ELE/ELET_UEBERDECKUNG_TRASSE' , 'Polyline' , [1000], 0])
def_array.append(['/ELE/ELE_BAUOBJEKT' , 'Point' , [1000], 0])
def_array.append(['/ELE/ELE_BAUOBJEKT_FLA' , 'Polygon' , [1000], 0])
def_array.append(['/ELE/ELE_BAUOBJEKT_LIN' , 'Polyline' , [1000], 0])
def_array.append(['/ELE/ELE_DIMENSION_200' , 'Polygon' , [1000], 0])
def_array.append(['/ELE/ELE_DIMENSION_500' , 'Polygon' , [1000], 0])
def_array.append(['/ELE/ELE_DS' , 'Polygon' , [500], 2316])
def_array.append(['/ELE/ELE_DS_KABELVERBINDUNG' , 'Polyline' , [500], 0])
def_array.append(['/ELE/ELE_DS_KLEMME' , 'Point' , [500], 0])
def_array.append(['/ELE/ELE_DS_LIN' , 'Polyline' , [500], 0])
def_array.append(['/ELE/ELE_DS_QUELLE' , 'Point' , [1000], 0])
def_array.append(['/ELE/ELE_DS_STATION' , 'Point' , [500], 0])
def_array.append(['/ELE/ELE_DS_SYMBOL' , 'Point' , [1000], 0])
def_array.append(['/ELE/ELE_DS_TRANSFORMER' , 'Point' , [1000], 0])
def_array.append(['/ELE/ELE_DS_TRENNPUNKT' , 'Point' , [500], 0])
def_array.append(['/ELE/ELE_DS_TXT_POS' , 'Point' , [200], 0])
def_array.append(['/ELE/ELE_DS_UEBERGANG' , 'Point' , [500], 0])
def_array.append(['/ELE/ELE_DS_VERBINDER' , 'Polyline' , [500], 0])
def_array.append(['/ELE/ELE_ERDUNG' , 'Polyline' , [500], 0])
def_array.append(['/ELE/ELE_ERDUNGSBRIDE' , 'Point' , [500], 0])
def_array.append(['/ELE/ELE_FREILEITUNGSABLEITER' , 'Point' , [1000], 0])
def_array.append(['/ELE/ELE_HAUSANSCHLUSS' , 'Point' , [500], 0])
def_array.append(['/ELE/ELE_INTVERBINDUNG' , 'Polyline' , [1000], 0])
def_array.append(['/ELE/ELE_KABEL' , 'Polyline' , [500], 0])
def_array.append(['/ELE/ELE_KLEINANSCHLUSS' , 'Point' , [500], 0])
def_array.append(['/ELE/ELE_LEUCHTE' , 'Point' , [500], 0])
def_array.append(['/ELE/ELE_LINIE' , 'Polyline' , [1000], 0])
def_array.append(['/ELE/ELE_MUFFE' , 'Point' , [500], 0])

def_array.append(['/ELE/ELE_QS_BASIS' , 'Polyline' , [500], 0])
def_array.append(['/ELE/ELE_QS_FLA' , 'Polygon' , [500], 0])
def_array.append(['/ELE/ELE_QS_KABEL' , 'Point' , [500], 0])
def_array.append(['/ELE/ELE_QS_LIN' , 'Polyline' , [1000], 0])
def_array.append(['/ELE/ELE_QS_ROHR' , 'Point' , [500], 0])
def_array.append(['/ELE/ELE_QS_ROHR_ROHR' , 'Point' , [1000], 0])
def_array.append(['/ELE/ELE_ROHR' , 'Polyline' , [200], 0])
def_array.append(['/ELE/ELE_SCHACHT' , 'Point' , [500], 0])
def_array.append(['/ELE/ELE_SCHACHT_FLA' , 'Polygon' , [500], 0])
def_array.append(['/ELE/ELE_SCHACHT_LIN' , 'Polyline' , [1000], 0])
def_array.append(['/ELE/ELE_SCHADEN' , 'Point' , [1000], 0])
def_array.append(['/ELE/ELE_SCHUTZSTREIFEN' , 'Polyline' , [1000], 0])
def_array.append(['/ELE/ELE_STATION' , 'Point' , [500], 0])
def_array.append(['/ELE/ELE_STATION_FLA' , 'Polygon' , [500], 0])
def_array.append(['/ELE/ELE_STATION_LIN' , 'Polyline' , [1000], 0])
def_array.append(['/ELE/ELE_SYMBOL' , 'Point' , [500], 0])
def_array.append(['/ELE/ELE_TRAGWERK' , 'Point' , [500], 0])
def_array.append(['/ELE/ELE_TRAGWERKTEIL' , 'Polyline' , [500], 0])
def_array.append(['/ELE/ELE_TRASSE' , 'Polyline' , [200], 0])
def_array.append(['/ELE/ELE_TRENNPUNKT' , 'Point' , [500], 0])
def_array.append(['/ELE/ELE_WP_MUFFE' , 'Point' , [500], 0])
def_array.append(['/ELE/ELE_WP_TRENNPUNKT' , 'Point' , [500], 0])
def_array.append(['/ELE/KONSTRUKTION_FLA' , 'Polygon' , [1000], 0])
def_array.append(['/ELE/KONSTRUKTION_LIN' , 'Polyline' , [1000], 0])
def_array.append(['/ELE/KONSTRUKTION_PKT' , 'Point' , [500], 0])
def_array.append(['/ELE/MESSPUNKT' , 'Point' , [1000], 0])
def_array.append(['/ELE/U_ELET_BAUMASSNAHME_TXT' , 'Polyline' , [500], 0])
def_array.append(['/ELE/U_ELET_DS_TXT' , 'Polyline' , [500], 0])
def_array.append(['/ELE/U_ELET_EEA_HAUSANSCHLUSS' , 'Polyline' , [500], 0])
def_array.append(['/ELE/U_ELET_EEA_TYP' , 'Polyline' , [500], 0])
def_array.append(['/ELE/U_ELET_ERDUNGSBRIDE_UEBERDECK' , 'Polyline' , [500], 0])
def_array.append(['/ELE/U_ELET_ERDUNG_UEBERDECK' , 'Polyline' , [500], 0])
def_array.append(['/ELE/U_ELET_KABEL_FLTRASSE' , 'Polyline' , [500], 0])
def_array.append(['/ELE/U_ELET_LTGPKT_BEMERK' , 'Polyline' , [500], 0])
def_array.append(['/ELE/U_ELET_LTGPKT_UEBERDECK' , 'Polyline' , [500], 0])
def_array.append(['/ELE/U_ELET_NR_VERSORGUNGSGEBIET' , 'Polyline' , [500], 0])
def_array.append(['/ELE/U_ELET_QS_BASIS' , 'Polyline' , [500], 0])
def_array.append(['/ELE/U_ELET_QS_FLA' , 'Polyline' , [500], 0])
def_array.append(['/ELE/U_ELET_SCHACHT_TXT' , 'Polyline' , [500], 0])
def_array.append(['/ELE/U_ELET_SCHLAUFE_NR' , 'Polyline' , [500], 0])
def_array.append(['/ELE/U_ELET_TRASSE_BEMERK' , 'Polyline' , [500], 0])
def_array.append(['/ELE/U_ELE_BAUMASSNAHME' , 'Point' , [500], 0])
def_array.append(['/ELE/U_ELE_BAUMASSNAHME_FLA' , 'Polygon' , [500], 0])
def_array.append(['/ELE/U_ELE_BAUMASSNAHME_LIN' , 'Polyline' , [500], 0])
def_array.append(['/ELE/U_ELE_EQUIPMENT' , 'Point' , [500], 0])
def_array.append(['/ELE/U_ELE_FERNSPEISUNG' , 'Polyline' , [500], 0])
def_array.append(['/ELE/U_ELE_LEITUNGSPUNKT' , 'Point' , [500], 0])
def_array.append(['/ELE/U_ELE_MUTPUNKT' , 'Point' , [500], 0])
def_array.append(['/ELE/U_ELE_SCHLAUFE' , 'Point' , [500], 0])
def_array.append(['/ELE/U_ELE_SCHLAUFE_FLA' , 'Polygon' , [500], 0])
def_array.append(['/ELE/U_ELE_VERSORGUNGSGEBIET' , 'Polygon' , [1000], 0])

def_array.append(['/ELE_PW1/ELET_PW1_KABEL' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW1/ELET_PW1_STATION' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW1/ELE_PW1_KABEL' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW1/ELE_PW1_MUFFE' , 'Point' , [1000], 0])
def_array.append(['/ELE_PW1/ELE_PW1_STATION' , 'Point' , [1000], 0])
def_array.append(['/ELE_PW1/ELE_PW1_TRENNPUNKT' , 'Point' , [1000], 0])

def_array.append(['/ELE_PW1000/ELET_PW1000_KABEL' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW1000/ELET_PW1000_KLEINANSCHLUSS' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW1000/ELET_PW1000_LEUCHTE' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW1000/ELET_PW1000_STATION' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW1000/ELET_PW1000_TRAGWERK' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW1000/ELET_PW1000_TRENNPUNKT' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW1000/ELE_PW1000_HAUSANSCHLUSS' , 'Point' , [1000], 0])
def_array.append(['/ELE_PW1000/ELE_PW1000_INTVERBINDUNG' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW1000/ELE_PW1000_KABEL' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW1000/ELE_PW1000_KLEINANSCHLUSS' , 'Point' , [1000], 0])
def_array.append(['/ELE_PW1000/ELE_PW1000_LEUCHTE' , 'Point' , [1000], 0])
def_array.append(['/ELE_PW1000/ELE_PW1000_MUFFE' , 'Point' , [1000], 0])
def_array.append(['/ELE_PW1000/ELE_PW1000_STATION' , 'Point' , [1000], 0])
def_array.append(['/ELE_PW1000/ELE_PW1000_STATION_FLA' , 'Polygon' , [1000], 0])
def_array.append(['/ELE_PW1000/ELE_PW1000_TRAGWERK' , 'Point' , [1000], 0])
def_array.append(['/ELE_PW1000/ELE_PW1000_TRASSE' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW1000/ELE_PW1000_TRENNPUNKT' , 'Point' , [1000], 0])

def_array.append(['/ELE_PW2/ELET_PW2_KABEL' , 'Polyline' , [500], 0])
def_array.append(['/ELE_PW2/ELET_PW2_NR_TRAGWERK' , 'Polyline' , [500], 0])
def_array.append(['/ELE_PW2/ELET_PW2_STATION' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW2/ELET_PW2_TRENNPUNKT' , 'Polyline' , [500], 0])
def_array.append(['/ELE_PW2/ELE_PW2_KABEL' , 'Polyline' , [500], 0])
def_array.append(['/ELE_PW2/ELE_PW2_MUFFE' , 'Point' , [1000], 0])

def_array.append(['/ELE_PW2/ELE_PW2_STATION' , 'Point' , [1000], 0])
def_array.append(['/ELE_PW2/ELE_PW2_TRAGWERK' , 'Point' , [1000], 0])
def_array.append(['/ELE_PW2/ELE_PW2_TRASSE' , 'Polyline' , [500], 0])
def_array.append(['/ELE_PW2/ELE_PW2_TRENNPUNKT' , 'Point' , [1000], 0])
def_array.append(['/ELE_PW2/U_ELET_PW2_STATION_NAME' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW2/U_ELET_PW2_STATION_NUMMER' , 'Polyline' , [1000], 0])

def_array.append(['/ELE_PW3/ELET_PW3_HAUSANSCHLUSS' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW3/ELET_PW3_KABEL' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW3/ELET_PW3_KLEINANSCHLUSS' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW3/ELET_PW3_NR_TRAGWERK' , 'Polyline' , [500], 0])
def_array.append(['/ELE_PW3/ELET_PW3_STATION' , 'Polyline' , [500], 0])
def_array.append(['/ELE_PW3/ELE_PW3_HAUSANSCHLUSS' , 'Point' , [200], 0])
def_array.append(['/ELE_PW3/ELE_PW3_KABEL' , 'Polyline' , [500], 0])
def_array.append(['/ELE_PW3/ELE_PW3_KLEINANSCHLUSS' , 'Point' , [500], 0])
def_array.append(['/ELE_PW3/ELE_PW3_MUFFE' , 'Point' , [500], 0])

def_array.append(['/ELE_PW3/ELE_PW3_STATION' , 'Point' , [500], 0])
def_array.append(['/ELE_PW3/ELE_PW3_TRASSE' , 'Polyline' , [500], 0])
def_array.append(['/ELE_PW3/ELE_PW3_TRENNPUNKT' , 'Point' , [1000], 0])
def_array.append(['/ELE_PW3/U_ELET_PW3_NR_STRANG' , 'Polyline' , [500], 0])
def_array.append(['/ELE_PW3/U_ELET_PW3_NR_TRENNPUNKT' , 'Polyline' , [500], 0])

def_array.append(['/ELE_PW4/ELET_PW4_KABEL' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW4/ELET_PW4_KLEINANSCHLUSS' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW4/ELET_PW4_LEUCHTE' , 'Polyline' , [500], 0])
def_array.append(['/ELE_PW4/ELET_PW4_NR_TRAGWERK' , 'Polyline' , [500], 0])
def_array.append(['/ELE_PW4/ELET_PW4_STATION' , 'Polyline' , [500], 0])
def_array.append(['/ELE_PW4/ELE_PW4_KABEL' , 'Polyline' , [500], 0])
def_array.append(['/ELE_PW4/ELE_PW4_KLEINANSCHLUSS' , 'Point' , [500], 0])
def_array.append(['/ELE_PW4/ELE_PW4_LEUCHTE' , 'Point' , [500], 0])
def_array.append(['/ELE_PW4/ELE_PW4_MUFFE' , 'Point' , [500], 0])

def_array.append(['/ELE_PW4/ELE_PW4_STATION' , 'Point' , [500], 0])
def_array.append(['/ELE_PW4/ELE_PW4_TRASSE' , 'Polyline' , [200], 0])
def_array.append(['/ELE_PW4/ELE_PW4_TRENNPUNKT' , 'Point' , [1000], 0])
def_array.append(['/ELE_PW4/U_ELET_PW4_NR_STRANG' , 'Polyline' , [500], 0])

def_array.append(['/ELE_PW6/ELET_PW6_KABEL' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW6/ELET_PW6_KLEINANSCHLUSS' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW6/ELET_PW6_STATION' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW6/ELE_PW6_HAUSANSCHLUSS' , 'Point' , [1000], 0])
def_array.append(['/ELE_PW6/ELE_PW6_KABEL' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW6/ELE_PW6_KLEINANSCHLUSS' , 'Point' , [1000], 0])
def_array.append(['/ELE_PW6/ELE_PW6_MUFFE' , 'Point' , [1000], 0])

def_array.append(['/ELE_PW6/ELE_PW6_STATION' , 'Point' , [1000], 0])
def_array.append(['/ELE_PW6/ELE_PW6_TRASSE' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW6/ELE_PW6_TRENNPUNKT' , 'Point' , [1000], 0])

def_array.append(['/ELE_PW7/ELET_PW7_HAUSANSCHLUSS' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW7/ELET_PW7_KABEL' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW7/ELET_PW7_KLEINANSCHLUSS' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW7/ELET_PW7_STATION' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW7/ELE_PW7_HAUSANSCHLUSS' , 'Point' , [1000], 0])
def_array.append(['/ELE_PW7/ELE_PW7_KABEL' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW7/ELE_PW7_KLEINANSCHLUSS' , 'Point' , [1000], 0])
def_array.append(['/ELE_PW7/ELE_PW7_MUFFE' , 'Point' , [1000], 0])

def_array.append(['/ELE_PW7/ELE_PW7_STATION' , 'Point' , [1000], 0])
def_array.append(['/ELE_PW7/ELE_PW7_TRASSE' , 'Polyline' , [1000], 0])
def_array.append(['/ELE_PW7/ELE_PW7_TRENNPUNKT' , 'Point' , [1000], 0])



