#-*- coding: utf-8 -*-
'''
Allgemeine Indexierung der Spatial Indexe

@author: Daniel Zinniker

@note: 



'''



# Variabeln

def_array=[]



def_array.append(['/DIV/KONSTRUKTION_FLA' , 'Polygon' , [500]])
def_array.append(['/DIV/KONSTRUKTION_PKT' , 'Point' , [500]])
def_array.append(['/DIV/KONSTRUKTION_LIN' , 'Polyline' , [500]])
def_array.append(['/DIV/MESSPUNKT' , 'Point' , [500]])
def_array.append(['/DIV/DIMENSION' , 'Polyline' , [500]])

def_array.append(['/WAS/WAS_ARMATUR' , 'Point' , [250]])
def_array.append(['/WAS/WAS_BAUMASSNAHMEN' , 'Point' , [1000]])
def_array.append(['/WAS/WAS_BMN_FLA' , 'Polygon' , [500]])
def_array.append(['/WAS/WAS_BMN_LIN' , 'Polyline' , [250]])
def_array.append(['/WAS/WAS_BMN_PKT' , 'Point' , [250]])
def_array.append(['/WAS/WAS_HAUSANSCHLUSS' , 'Point' , [250]])
def_array.append(['/WAS/WAS_HYDRANT' , 'Point' , [1000]])
def_array.append(['/WAS/WAS_HYDRAULIK_KNOTEN_PKT' , 'Point' , [1000]])
def_array.append(['/WAS/WAS_HYDRAULIK_STRANG_LIN' , 'Polyline' , [1000]])
def_array.append(['/WAS/WAS_KABEL' , 'Polyline' , [250]])
def_array.append(['/WAS/WAS_KABEL_PKT' , 'Point' , [1000]])
def_array.append(['/WAS/WAS_KKS' , 'Point' , [1000]])
def_array.append(['/WAS/WAS_LEITUNGSPUNKT' , 'Point' , [250]])
def_array.append(['/WAS/WAS_LINIE' , 'Polyline' , [500]])
def_array.append(['/WAS/WAS_ROHRLEITUNGSTEIL' , 'Point' , [250]])
def_array.append(['/WAS/WAS_SBW_FLA' , 'Polygon' , [500]])
def_array.append(['/WAS/WAS_SBW_LIN' , 'Polyline' , [500]])
def_array.append(['/WAS/WAS_SBW_PKT' , 'Point' , [500]])
def_array.append(['/WAS/WAS_SCHADEN' , 'Point' , [500]])
def_array.append(['/WAS/WAS_SPEZIALBAUWERK' , 'Point' , [1000]])
def_array.append(['/WAS/WAS_TOPO_LIN' , 'Polyline' , [250]])
def_array.append(['/WAS/WAS_UEBRIGE_PKT' , 'Point' , [250]])
def_array.append(['/WAS/WAS_LEITUNG' , 'Polyline' , [200]])
def_array.append(['/WAS/WAS_SCHUTZZONE_FLA' , 'Polygon' , [1000]])
def_array.append(['/WAS/WAS_NET_Junctions' , 'Point' , [200]])
def_array.append(['/WAS/U_WAS_ABWASSER' , 'Polyline' , [500]])
def_array.append(['/WAS/U_WAS_MUTPUNKT' , 'Point' , [1000]])
def_array.append(['/WAS/WAS_DETAILPUNKT' , 'Point' , [500]])
def_array.append(['/WAS/WAS_DRUCKZONE_FLA' , 'Polygon' , [500]])
def_array.append(['/WAS/WAS_EINSTIEG' , 'Point' , [500]])
def_array.append(['/WAS/WAS_SCHUTZGEBIET_FLA' , 'Polygon' , [500]])
def_array.append(['/WAS/WAS_VERSORGUNGSBEZIRK' , 'Polygon' , [500]])

def_array.append(['/WAS_LABEL/WAST_BEMERKUNG_LTG' , 'Polyline' , [500]])
def_array.append(['/WAS_LABEL/WAST_MATDURCH_LTG' , 'Polyline' , [500]])
def_array.append(['/WAS_LABEL/WAST_NAME_SPEZIALBW' , 'Polyline' , [500]])
def_array.append(['/WAS_LABEL/WAST_SCHALT_ARMATUR' , 'Polyline' , [500]])
def_array.append(['/WAS_LABEL/WAST_TEXT' , 'Polyline' , [500]])
def_array.append(['/WAS_LABEL/WAST_UEBERDECKUNG_LTG' , 'Polyline' , [500]])
def_array.append(['/WAS_LABEL/WAST_MATTYPMESS_BMN' , 'Polyline' , [500]])
def_array.append(['/WAS_LABEL/WAST_TEXT_KABEL' , 'Polyline' , [500]])
def_array.append(['/WAS_LABEL/WAST_TEXT_KABEL_PKT' , 'Polyline' , [500]])
def_array.append(['/WAS_LABEL/WAST_NAME_HYDR_KNOTEN' , 'Polyline' , [500]])
def_array.append(['/WAS_LABEL/WAST_NUMMER_ARMATUR' , 'Polyline' , [500]])
def_array.append(['/WAS_LABEL/WAST_NUMMER_HAUSAN' , 'Polyline' , [500]])
def_array.append(['/WAS_LABEL/WAST_NUMMER_HYD_STRANG' , 'Polyline' , [500]])
def_array.append(['/WAS_LABEL/WAST_NUMMER_HYDR' , 'Polyline' , [500]])
def_array.append(['/WAS_LABEL/WAST_NUMMER_ROHRT' , 'Polyline' , [500]])
def_array.append(['/WAS_LABEL/U_WAST_BEMERK_LTG_PKT' , 'Polyline' , [500]])
def_array.append(['/WAS_LABEL/U_WAST_BEMERK_RLTG' , 'Polyline' , [500]])
def_array.append(['/WAS_LABEL/U_WAST_BEMERK_SBW' , 'Polyline' , [500]])
def_array.append(['/WAS_LABEL/U_WAST_DETAIL_UP_ARMATUR' , 'Polyline' , [500]])
def_array.append(['/WAS_LABEL/U_WAST_DETAIL_UP_HYDRANT' , 'Polyline' , [500]])
def_array.append(['/WAS_LABEL/U_WAST_DETAIL_UP_MATDURCH' , 'Polyline' , [500]])
def_array.append(['/WAS_LABEL/U_WAST_DETAIL_UP_SBW_NAME' , 'Polyline' , [500]])
def_array.append(['/WAS_LABEL/U_WAST_MATDURCH_ABW' , 'Polyline' , [500]])
def_array.append(['/WAS_LABEL/U_WAST_NUMMER_ARMATUR' , 'Polyline' , [500]])
def_array.append(['/WAS_LABEL/U_WAST_UEBERDECK_BAUMASSN' , 'Polyline' , [500]])
def_array.append(['/WAS_LABEL/U_WAST_UEBERDECK_LTGPKT' , 'Polyline' , [500]])
def_array.append(['/WAS_LABEL/U_WAST_UEBERDECK_ROHRLTGTEIL' , 'Polyline' , [500]])

def_array.append(['/WAS_PW2/WAS_PW2_LEITUNG' , 'Polyline' , [500]])
def_array.append(['/WAS_PW2/WAS_PW2_TOPO_LIN' , 'Polyline' , [500]])
def_array.append(['/WAS_PW2/WAS_PW2_HAUSANSCHLUSS' , 'Point' , [500]])
def_array.append(['/WAS_PW2/WAS_PW2_HYDRANT' , 'Point' , [500]])
def_array.append(['/WAS_PW2/WAS_PW2_KKS' , 'Point' , [500]])
def_array.append(['/WAS_PW2/WAS_PW2_ROHRLEITUNGSTEIL' , 'Point' , [500]])
def_array.append(['/WAS_PW2/WAS_PW2_SPEZIALBAUWERK' , 'Point' , [500]])
def_array.append(['/WAS_PW2/WAS_PW2_ARMATUR' , 'Point' , [500]])
def_array.append(['/WAS_PW2/WAS_PW2_UEBRIGE_PKT' , 'Point' , [500]])
def_array.append(['/WAS_PW2/WAS_PW2_KABEL' , 'Polyline' , [500]])
def_array.append(['/WAS_PW2/WAS_PW2_KABEL_PKT' , 'Point' , [500]])
def_array.append(['/WAS_PW3/WAS_PW2_SYMBOL_HYDRANT' , 'Point' , [500]])
def_array.append(['/WAS_PW2/WAST_PW2_DURCHM_LTG' , 'Polyline' , [500]])
def_array.append(['/WAS_PW2/WAST_PW2_NUMMER_HYDR' , 'Polyline' , [500]])
def_array.append(['/WAS_PW2/WAST_PW2_NAME_SPEZIALBW' , 'Polyline' , [500]])
def_array.append(['/WAS_PW2/WAST_PW2_NUMMER_ARMATUR' , 'Polyline' , [500]])
def_array.append(['/WAS_PW2/WAST_PW2_ENTNAHME_HYDR' , 'Polyline' , [500]])
def_array.append(['/WAS_PW2/WAST_PW2_FLIESSDRUCK_HYDR' , 'Polyline' , [500]])
def_array.append(['/WAS_PW2/WAST_PW2_TEXT_PUMPWERK' , 'Polyline' , [500]])
def_array.append(['/WAS_PW2/WAST_PW2_TEXT_RESERVOIR' , 'Polyline' , [500]])
def_array.append(['/WAS_PW2/WAST_PW2_VERSORGUNGSDRUCK_HYDR' , 'Polyline' , [500]])

def_array.append(['/WAS_PW3/WAS_PW3_TOPO_LIN' , 'Polyline' , [500]])
def_array.append(['/WAS_PW3/WAS_PW3_ARMATUR' , 'Point' , [500]])
def_array.append(['/WAS_PW3/WAS_PW3_HAUSANSCHLUSS' , 'Point' , [500]])
def_array.append(['/WAS_PW3/WAS_PW3_HYDRANT' , 'Point' , [500]])
def_array.append(['/WAS_PW3/WAS_PW3_LEITUNG' , 'Polyline' , [500]])
def_array.append(['/WAS_PW3/WAS_PW3_SPEZIALBAUWERK' , 'Point' , [500]])
def_array.append(['/WAS_PW3/WAS_PW3_KABEL' , 'Polyline' , [500]])
def_array.append(['/WAS_PW3/WAS_PW3_KABEL_PKT' , 'Point' , [500]])
def_array.append(['/WAS_PW3/WAS_PW3_KKS' , 'Point' , [500]])
def_array.append(['/WAS_PW3/WAS_PW3_ROHRLEITUNGSTEIL' , 'Point' , [500]])
def_array.append(['/WAS_PW3/WAS_PW3_UEBRIGE_PKT' , 'Point' , [500]])
def_array.append(['/WAS_PW3/WAS_PW3_NET_Junctions' , 'Point' , [500]])
def_array.append(['/WAS_PW3/WAST_PW3_DURCHM_LTG' , 'Polyline' , [500]])
def_array.append(['/WAS_PW3/WAST_PW3_NUMMER_HYDR' , 'Polyline' , [500]])
def_array.append(['/WAS_PW3/WAST_PW3_NAME_SPEZIALBW' , 'Polyline' , [500]])
def_array.append(['/WAS_PW3/WAST_PW3_NUMMER_ARMATUR' , 'Polyline' , [500]])
def_array.append(['/WAS_PW3/WAS_PW3_SYMBOL_HYDRANT' , 'Point' , [500]])
def_array.append(['/WAS_PW3/WAST_PW3_ENTNAHME_HYDR' , 'Polyline' , [500]])
def_array.append(['/WAS_PW3/WAST_PW3_FLIESSDRUCK_HYDR' , 'Polyline' , [500]])
def_array.append(['/WAS_PW3/WAST_PW3_TEXT_PUMPWERK' , 'Polyline' , [500]])
def_array.append(['/WAS_PW3/WAST_PW3_TEXT_RESERVOIR' , 'Polyline' , [500]])
def_array.append(['/WAS_PW3/WAST_PW3_VERSORGUNGSDRUCK_HYDR' , 'Polyline' , [500]])
def_array.append(['/WAS_PW3/U_WAS_PW3_DETAILLINIE' , 'Polyline' , [500]])
def_array.append(['/WAS_PW3/U_WAS_PW3_ZUSATZSYMBOL' , 'Point' , [500]])
def_array.append(['/WAS_PW3/U_WAST_PW3_UP_TEXT' , 'Polyline' , [500]])

def_array.append(['/WAS_PWD/GNPWD_URSPRUNG' , 'Polygon' , [500]])
def_array.append(['/WAS_PWD/GNPWD_ABBILD' , 'Polygon' , [500]])
def_array.append(['/WAS_PWD/GNPWD_VERBINDUNG' , 'Polyline' , [500]])
def_array.append(['/WAS_PWD/WAS_PWD_ARMATUR' , 'Point' , [500]])
def_array.append(['/WAS_PWD/WAS_PWD_HAUSANSCHLUSS' , 'Point' , [500]])
def_array.append(['/WAS_PWD/WAS_PWD_HYDRANT' , 'Point' , [500]])
def_array.append(['/WAS_PWD/WAS_PWD_KABEL' , 'Polyline' , [500]])
def_array.append(['/WAS_PWD/WAS_PWD_KABEL_PKT' , 'Point' , [500]])
def_array.append(['/WAS_PWD/WAS_PWD_KKS' , 'Point' , [500]])
def_array.append(['/WAS_PWD/WAS_PWD_LEITUNG' , 'Polyline' , [500]])
def_array.append(['/WAS_PWD/WAS_PWD_ROHRLEITUNGSTEIL' , 'Point' , [500]])
def_array.append(['/WAS_PWD/WAS_PWD_SBW_PKT' , 'Point' , [500]])
def_array.append(['/WAS_PWD/WAS_PWD_SBW_LIN' , 'Polyline' , [500]])
def_array.append(['/WAS_PWD/WAS_PWD_SBW_FLA' , 'Polygon' , [500]])
def_array.append(['/WAS_PWD/WAS_PWD_SPEZIALBAUWERK' , 'Point' , [500]])
def_array.append(['/WAS_PWD/WAS_PWD_UEBRIGE_PKT' , 'Point' , [500]])
def_array.append(['/WAS_PWD/WAST_PWD_BEMERKUNG_LTG' , 'Polyline' , [500]])
def_array.append(['/WAS_PWD/WAST_PWD_MATDURCH_LTG' , 'Polyline' , [500]])
def_array.append(['/WAS_PWD/WAST_PWD_NAME_SPEZIALBW' , 'Polyline' , [500]])
def_array.append(['/WAS_PWD/WAST_PWD_SCHALT_ARMATUR' , 'Polyline' , [500]])
def_array.append(['/WAS_PWD/WAST_PWD_UEBERDECKUNG_LTG' , 'Polyline' , [500]])
def_array.append(['/WAS_PWD/WAST_PWD_NUMMER_HYDR' , 'Polyline' , [500]])
def_array.append(['/WAS_PWD/WAST_PWD_NAME_ABBILD' , 'Polyline' , [500]])
def_array.append(['/WAS_PWD/WAST_PWD_NAME_URSPRUNG' , 'Polyline' , [500]])
def_array.append(['/WAS_PWD/WAST_PWD_NUMMER_ARMATUR' , 'Polyline' , [500]])
def_array.append(['/WAS_PWD/WAST_PWD_NUMMER_HAUSAN' , 'Polyline' , [500]])
def_array.append(['/WAS_PWD/WAST_PWD_NUMMER_ROHRT' , 'Polyline' , [500]])


